# Generated by Django 4.1.7 on 2023-03-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
