# Generated by Django 4.1.7 on 2023-03-15 11:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='From',
            field=models.TimeField(default='11:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='To',
            field=models.TimeField(default='11:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='License',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
    ]
