# Generated by Django 4.1.7 on 2023-03-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaladmin', '0001_initial'),
        ('doctor', '0004_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaladmin.specialty'),
        ),
    ]
