# Generated by Django 4.1.7 on 2023-03-16 01:07

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_reservation'),
        ('doctor', '0005_alter_doctor_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField()),
                ('Time', models.TimeField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_File', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.reservation')),
            ],
        ),
    ]
