# Generated by Django 4.1.7 on 2023-03-16 11:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_prescription_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Image_File',
        ),
        migrations.CreateModel(
            name='Image_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_File', models.ImageField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
    ]
