# Generated by Django 4.1.7 on 2023-03-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_prescription_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Prescription_Image',
        ),
        migrations.RenameModel(
            old_name='Image_File',
            new_name='Prescription_Image_File',
        ),
    ]
