# Generated by Django 4.1.7 on 2023-03-16 11:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_rename_image_prescription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_image_file',
            name='Image_File',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
    ]
