# Generated by Django 4.1.7 on 2023-03-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_prescription_image_file_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_image_file',
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Prescription_Image',
        ),
        migrations.DeleteModel(
            name='Prescription_Image_File',
        ),
    ]
