# Generated by Django 4.1.7 on 2023-03-16 11:59

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_prescription_image_file_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription_Image_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_File', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Body3', models.TextField(blank=True, null=True)),
                ('Bodys', models.TextField(blank=True, null=True)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('Body2', models.TextField(blank=True, null=True)),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctor.prescription')),
            ],
        ),
    ]
