# Generated by Django 4.1.7 on 2023-03-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_prescription_image_file_prescription_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_image',
            name='Body2',
        ),
        migrations.RemoveField(
            model_name='prescription_image_file',
            name='Body3',
        ),
        migrations.RemoveField(
            model_name='prescription_image_file',
            name='Bodys',
        ),
        migrations.AlterField(
            model_name='prescription_image',
            name='Prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription_image_file',
            name='Prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription'),
        ),
    ]
